import { IsNotEmpty, IsOptional, IsString } from "class-validator";
import { UpdateSampleDto } from "./update-sample.dto";

export class CreateSampleDto extends UpdateSampleDto {
  /**
   * Globally unique identifier of a sample. This could be provided as an input value or generated by the system.
   */
  @IsString()
  @IsOptional()
  readonly sampleId?: string;

  /**
   * The name of the sample.
   */
  @IsString()
  @IsNotEmpty()
  declare readonly sampleName: string;
}
